### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Guekka** [tcbrindle/libflow#6]
Could you please add a license to this repository? `vcpkg` wants a license, so I had to give it a fake one. Which is not... ideal, from a legal standpoint

**Comment by tcbrindle** [comment]
Yes, I should have done this already before I made the GitHub repo public. For the record, libflow is (or will be) covered by the [Boost Software License](https://www.boost.org/LICENSE_1_0.txt)

**Comment by tcbrindle** [comment]
This should now be done, let me know if there are any files I've forgotten
